#
# =======================================
# AUTHOR        : Claudio Prato @ Team EA
#               : Davide Celano @ Team EA
# CREATE DATE   : 2023/09/12
# PURPOSE       : Setup the Elasticsearch Operator
# SPECIAL NOTES :
# =======================================
#
# :::
# ::: Create the Namespace: openshift-operators-redhat
# :::
apiVersion: v1
kind: Namespace
metadata:
  name: openshift-operators-redhat 
  annotations:
    openshift.io/node-selector: ""
  labels:
    openshift.io/cluster-monitoring: "true" 
---
# :::
# ::: Elasticsearch: OperatorGroup
# :::
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: openshift-operators-redhat
  namespace: openshift-operators-redhat
## you can omit the following "spec.targetNamespaces" to specify a global Operator group,
## which selects all namespaces
spec: {}
# spec:
#   targetNamespaces:
#   - openshift-operators-redhat
---
# :::
# ::: Elasticsearch: Operator Subscription
# :::
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  # annotations:
  #   template.alpha.openshift.io/wait-for-ready: "true"
  name: elasticsearch-operator
  # For AllNamespaces install mode usage, specify the 'openshift-operators' namespace.
  # Otherwise, specify the relevant single namespace for SingleNamespace install mode usage.
  # look for installModes by command: 'oc get packagemanifests elasticsearch-operator -o yaml'
  namespace: openshift-operators-redhat
  labels:
    # operators.coreos.com/elasticsearch-operator.openshift-operators-redhat: ''
    app: es-logging-dedalus
spec:
  # Name of the channel to subscribe to.
  # look for the channel version available by command: 'oc get packagemanifests elasticsearch-operator -o yaml'
  channel: stable
  # Set the approval strategy to Manual in case your specified version is superseded by a later version in the catalog.
  # This plan prevents an automatic upgrade to a later version and requires manual approval before the starting CSV can complete the installation.
  installPlanApproval: Automatic
  # Name of the Operator to subscribe to
  name: elasticsearch-operator
  # Name of the catalog source that provides the Operator.
  # you can choose among 'redhat-operators' and 'community-operators'
  source: redhat-operators
  # Namespace of the catalog source. Use openshift-marketplace for the default OperatorHub catalog sources.
  sourceNamespace: openshift-marketplace
  # Set a specific version of an Operator CSV
  startingCSV: elasticsearch-operator.v5.8.6